### ISSUE TITLE
Add RMR to common versions

### ISSUE THREAD

**Issue by Lyxnx** [Lyxnx/android-gradle-catalogs#98]
```toml
[versions]
redmadrobot = "0.18.1"

[plugins]
redmadrobot-android-config = { id = "com.redmadrobot.android-config", version.ref = "redmadrobot" }
redmadrobot-android-application = { id = "com.redmadrobot.application", version.ref = "redmadrobot" }
redmadrobot-android-library = { id = "com.redmadrobot.android-library", version.ref = "redmadrobot" }
redmadrobot-kotlin-library = { id = "com.redmadrobot.kotlin-library", version.ref = "redmadrobot" }
```
