### ISSUE TITLE
Add standard material to common versions

### ISSUE THREAD

**Issue by Lyxnx** [Lyxnx/android-gradle-catalogs#99]
```toml
[versions]
material = "1.8.0"

[libraries]
material = { module = "com.google.android.material:material", version.ref = "material" }
```
